config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



  resources :projects do
    collection do
        get 'vr', to: 'projects#vr'
    end
    member do
      get 'showvr', to: 'projects#showvr'
      get 'lastest', to: 'projects#lastest'
    end
    resources :artworks, only: [:new, :create, :edit, :show, :showvr, :update, :destroy ], shallow: true

  end

  resources :artworks, only: [:index]

resources :infos, only: [:index, :new, :create, :edit, :show, :update, :destroy]

resources :events, only: [:index, :new, :create, :edit, :show, :update, :destroy]

resources :texts, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  belongs_to :project

default_scope { order(ranking: :asc)}




  mount_uploader :photo, PhotoUploader

  CATEGORIES2 =%w( artwork illustration )

def previous
  artworks = self.class.where('project_id = ?', self.project_id )
  artworks.where('ranking < ?', self.ranking).last
end

def next
  artworks = self.class.where('project_id = ?', self.project_id )

  artworks.where('ranking > ?', self.ranking).first

end

validates :title, presence: true
  validates :description, presence: true
  validates :ranking, presence: true
  validates :date, presence: true
  validates :project_id, presence:true
  validates :category, inclusion: { in: CATEGORIES2 }, presence: true

end

app/models/event.rb
class Event < ApplicationRecord
   default_scope { order(id: :desc)}

   mount_uploader :photo, PhotoUploader


   CATEGORIES =%w( last second other )

  validates :category, inclusion: { in: CATEGORIES }, presence: true
  validates :name, presence: true
  validates :date, presence: true
  validates :localisation, presence: true
end

app/models/info.rb
class Info < ApplicationRecord
default_scope { order(id: :desc)}


CHOICES =%w( SHOWING RESIDENCE SCENOGRAPHY TEACHING PRIZE MEDIAS)




  validates :category, inclusion: { in: CHOICES }, presence: true
  validates :name, presence: true
  validates :date, presence: true
  validates :localisation, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  default_scope { order(ranking: :asc)}

has_many :artworks
mount_uploader :photo, PhotoUploader

CATEGORIES =%w( drawing painting virtual_reality other_project )


def previous
  projects = self.class.where.not({id: '1'})
  projects.where('ranking < ?', self.ranking).last

end

def next
  projects = self.class.where.not({id: '1'})
   projects.where('ranking > ?', self.ranking).first
end

def previous_vr

  projects = self.class.where({category: 'virtual_reality'})

  projects.where('ranking < ?', self.ranking).last
end

def next_vr

  projects = self.class.where({category: 'virtual_reality'})
   projects.where('ranking > ?', self.ranking).first
end



  validates :name, presence: true
  validates :presentation, presence: true
  validates :category, inclusion: { in: CATEGORIES }, presence: true
  validates :photo, presence: true
  validates :date, presence: true
  validates :ranking, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
    default_scope { order(id: :desc)}

   validates :content, presence: true
  validates :author, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show, :showvr, :illustration]

  before_action :set_project, only: [:new, :create]
  before_action :find_artwork, only: [:show, :edit, :update, :destroy, :showvr, :illustration]

  def index
    @artworks = Artwork.all
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)
    @artwork.project = @project

    if @artwork.save
      redirect_to artwork_path(@artwork)
    else
      render 'artworks/new'
    end
  end

  def edit
  end

  def show
  end

  def illustration
  end

  def showvr
  end


  def update
     @artwork.update(artwork_params)
    redirect_to artwork_path(@artwork)
  end

  def destroy
    @artwork.destroy
    redirect_to projects_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

   def find_artwork
    @artwork = Artwork.find(params[:id])
  end

  def artwork_params
    params.require(:artwork).permit(:title, :project_id, :description, :format, :date, :ranking, :category, :photo)
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   skip_before_action :authenticate_user!, only: [:index]

  before_action :set_event, only: [:edit, :show, :update, :destroy]


  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
    redirect_to events_path  else
    render 'events/new'
  end

  end

  def edit
  end




  def update
     @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end




  private

  def set_event
    @event = Event.find(params[:id])
  end


  def event_params
    params.require(:event).permit(:category, :name, :date, :localisation, :information, :photo)
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController


skip_before_action :authenticate_user!, only: [:index]

before_action :set_info, only: [:edit, :update, :destroy]


  def index
    @infos = Info.all
  end

  def new
    @info = Info.new
  end

  def create
    @info = Info.new(info_params)

    if @info.save
    redirect_to infos_path  else
    render 'infos/new'
    end

  end

  def edit
  end






  def update
     @info.update(info_params)
    redirect_to infos_path
  end

  def destroy
    @info.destroy
    redirect_to infos_path
  end





  private

  def set_info
    @info = Info.find(params[:id])
  end


  def info_params
    params.require(:info).permit(:category, :name, :date, :localisation, :commentary)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

skip_before_action :authenticate_user!, only: [:index, :show, :vr, :showvr, :lastest]

before_action :set_project, only: [:show, :edit, :update, :destroy, :showvr, :lastest]



def index

  @projects = Project.all

end

def new
  @project = Project.new
end

def create
  @project = Project.new(project_params)
  if @project.save
    redirect_to project_path(@project)
  else
    render 'projects/new'
  end
end

  def edit
  end

  def show

  end

  def showvr

  end

  def lastest
  end


  def update
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end


def vr
  @projects = Project.where(category: 'virtual_reality')
end


  private


  def set_project
    @project = Project.find(params[:id])
  end


  def project_params
    params.require(:project).permit(:name, :name2, :category, :presentation, :photo, :date, :ranking, :commentary)
  end


end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index]

  before_action :set_text, only: [:edit, :update, :destroy]


  def index
    @texts = Text.all
  end

  def new
    @text = Text.new
  end

  def create
    @text = Text.new(text_params)

    if @text.save
    redirect_to texts_path
  else
    render 'texts/new'
  end

  end

  def edit
  end




  def update
     @text.update(text_params)
    redirect_to texts_path
  end

  def destroy
    @text.destroy
    redirect_to texts_path
  end



  private

  def set_text
    @text = Text.find(params[:id])
  end


  def text_params
    params.require(:text).permit(:content, :author, :presentation_author)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<%= render 'shared/forms/form_event' %>

app/views/events/new.html.erb
<%= render 'shared/forms/form_event' %>

app/views/infos/edit.html.erb
<%= render 'shared/forms/form_info' %>

app/views/infos/new.html.erb
<%= render 'shared/forms/form_info' %>

app/views/projects/edit.html.erb
<%= render 'shared/forms/form_project' %>

app/views/projects/index.html.erb
<div class= "page hidden-xs">

  <%= render 'shared/navbar/navbar' %>

  <div class="skeleton text-center hidden-xs">

    <div class="skeleton-left text-center">
      <div class="link-border-container">
        <div id= "link-rotate-right">
          <%=link_to "- texts -", texts_path, class: "link-border"%>
        </div>
      </div>
    </div>

    <div class="skeleton-middle text-center" >
      <div class="projects-content hidden-xs">
          <%= render 'shared/projects/projects_content' %>
      </div>
      <div class="projects-content-xs hidden-sm hidden-md hidden-lg ">
          <%= render 'shared/projects/projects_content' %>
      </div>
    </div>

    <div class="skeleton-right text-center">
      <div class="link-border-container">
        <div id="link-rotate-left">
         <%#=link_to "- shop -", artworks_path, class: "link-border" %>
         <%=link_to "- EVENTS -", events_path, class: "link-border-news" %>
        </div>
      </div>
    </div>

  </div>
</div>




<div class= "page hidden-sm hidden-md hidden-lg">

  <%= render 'shared/navbar/navbar_xs'%>
  <div class="skeleton text-center hidden-sm hidden-md hidden-lg">
    <div class="skeleton-middle-xs text-center" >
      <div class="projects-content-xs hidden-sm hidden-md hidden-lg ">
          <%= render 'shared/projects/projects_content_xs' %>
      </div>
    </div>
  </div>
</div>

app/views/projects/lastest.html.erb
<%= render 'shared/navbar/navbar' %>
<%#= render 'shared/navbar/navbar_project_xs'%>


<div class="skeleton text-center">

  <div class="skeleton-left text-center">
    <div class="link-border-container">
    <div id="link-rotate-right">




    </div>
    </div>
  </div>


  <div class="skeleton-middle text-center">
    <div class="project">


      <div class= "project-tools">
        <div>
          <% if current_user %>

          <a href="" class="link-admin">
              <%= link_to "update |", edit_project_path(@project), class: "link" %>
              </a>
          <a href="" class="link-admin">
              <%#= link_to " new artwork", new_project_artwork_path(@project), class: "link" %>
              </a>
            <% end %>
        </div>
        <div></div>
      </div>




        <div class=project-presentation>
          <p class="project-project-name-xs hidden-sm hidden-md hidden-lg" ><%= @project.name %><span> </span><%= @project.name2%></p>
          <p class="project-project-name hidden-xs" ><%= @project.name%><span> </span><%=@project.name2%></p>
          <p class="project-project-presentation hidden-xs"><%= @project.presentation%></p>
          <p class="project-project-presentation-xs hidden-sm hidden-md hidden-lg"><%= @project.presentation%></p>
          <p class="project-project-date"><%=@project.date%></p>
          <p class="project-project-commentary hidden-xs"><%= simple_format(@project.commentary, class: "project-project-commentary hidden-xs")%></p>
          <p class="project-project-commentary-xs hidden-sm hidden-md hidden-lg"><%= simple_format(@project.commentary, class: "project-project-commentary-xs hidden-sm hidden-md hidden-lg") %></p>
        </div>




<div class="project-artworks-container">
          <div class="hidden-box hidden-xs"></div>
          <div class="hidden-box-xs hidden-sm hidden-md hidden-lg"></div>
            <div class="row">


              <%# @project.artworks.each do |artwork| %>
                <div class="col-xs-12" >
                  <div class="artwork-photo-card">
                    <div class= "artwork-photo" >

                      <a class="artwork-photo-link" href="<%#= artwork_path(artwork) %>">
                        <p class="hidden-xs hidden-sm ">
                        <%#=cl_image_tag artwork.photo, height: 600, crop: :scale %>
                      </p>
                      <p class=" hidden-md hidden-lg">
                        <%#=cl_image_tag artwork.photo, height: 230, crop: :scale %>
                      </p>
                    </a>
                    </div>
              <div class="artwork-photo-description text-center">

                <a class="artwork-photo-title-link" href="<%#= artwork_path(artwork) %>"><%#= artwork.title %> (<%#= artwork.date%>)</a>
              </div>
            </div>
          </div>
        <%# end %>

    </div>
  <div class="hidden-box-bottom-xs hidden-lg"></div>
</div>


</div>
</div>


  <div class="skeleton-right text-center">
  <div class="link-border-container">
    <div id="link-rotate-left"><%= link_to "- home -", projects_path,  class:"link-border" %></div>
  </div>
</div>

</div>

app/views/projects/new.html.erb
<%= render 'shared/forms/form_project' %>

app/views/projects/showvr.html.erb
<div class= "page hidden-xs">
  <%= render 'shared/navbar/navbar_project' %>

  <div class="skeleton text-center">

    <div class="skeleton-left text-center">
      <div class="link-border-container">
        <div id="link-rotate-right">
          <%= link_to "- virtual reality -", vr_projects_path,  class:"link-border" %>
        </div>
      </div>
    </div>


    <div class="skeleton-middle text-center">
      <div class="project">

        <div class= 'projects-controls-row hidden-xs'>
          <div class= 'projects-controls-row-div'></div>
          <div class = 'projects-controls-row-div'>
            <%= render 'shared/project/projects_vr_controls' %>
          </div>
        </div>

        <div class=project-presentation>
          <p class="project-project-name hidden-xs" ><%= @project.name%><span> </span><%=@project.name2%></p>
          <p class="project-project-presentation hidden-xs"><%= @project.presentation%></p>
          <p class="project-project-date"><%=@project.date%></p>
          <p class="project-project-commentary hidden-xs"><%= simple_format(@project.commentary, class: "project-project-commentary hidden-xs")%></p>

        </div>

        <div class="project-artworks-container hidden-xs">
          <div class="hidden-box hidden-xs"></div>
          <%= render 'shared/project/project_artworks_container' %>
        </div>


      </div>
    </div>


    <div class="skeleton-right text-center">
      <div class="link-border-container">
        <div id="link-rotate-left"><%= link_to "- EVENTS -", events_path, class:"link-border"%></div>
      </div>
    </div>

  </div>
</div>



<div class= "page hidden-sm hidden-md hidden-lg">


<%= render 'shared/navbar/navbar_project_vr_xs'%>

  <div class="skeleton text-center">

    <div class="skeleton-middle-xs text-center">
      <div class="project">

        <div class= 'projects-controls-row hidden-sm hidden-md hidden-lg'>
          <div class = 'projects-controls-row-div-xs'>
            <%#= render 'shared/project/projects_vr_controls' %>
          </div>
        </div>

        <div class=project-presentation>
          <p class="project-project-name-xs hidden-sm hidden-md hidden-lg" ><%= @project.name %><span> </span><%= @project.name2%></p>
          <p class="project-project-presentation-xs hidden-sm hidden-md hidden-lg"><%= @project.presentation%></p>
          <p class="project-project-date"><%=@project.date%></p>
          <p class="project-project-commentary-xs hidden-sm hidden-md hidden-lg"><%= simple_format(@project.commentary, class: "project-project-commentary-xs hidden-sm hidden-md hidden-lg") %></p>
        </div>
        <div class="project-artworks-container-xs hidden-sm hidden-md hidden-lg ">
        <div class="hidden-box-xs hidden-sm hidden-md hidden-lg"></div>
          <%= render 'shared/project/project_artworks_container' %>
        </div>
         <div class= 'project-icons'>
          <%= render 'shared/icons' %>
        </div>

      </div>
    </div>

  </div>


</div>

app/views/projects/vr.html.erb
<div class="page hidden-xs">

  <%= render 'shared/navbar/navbar' %>

  <div class="skeleton text-center hidden-xs">

    <div class="skeleton-left text-center">
      <div class="link-border-container">
        <div class= "link-left" id="link-rotate-right">
          <%=link_to "- home -", projects_path, class: "link-border" %>
        </div>
      </div>
    </div>

    <div class="skeleton-middle text-center" >

      <div class="projects-top-bottom hidden-xs">
        <div class="title-vr">
          VIRTUAL | REALITY
        </div>
      </div>


      <div class="projects-vr">
        <div class="row">
          <% @projects.each do |project| %>
            <div class="col-xs-12">
              <div class="project-card-vr" >
                <div class="project-name">
                  <div id="project-path"><%= link_to project.name, showvr_project_path(project), class: "link-project-vr"%></div>
                  </div>
                </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="projects-top-bottom hidden-xs">
        <div class= "top-bottom-shadow"></div>
          <div class= "projects-title-bottom">
        <div><%= link_to "VR | PERFORMANCE", "https://vimeo.com/213874707", class: "link-bottom-title"%>
        </div>
      </div>
      </div>

    </div>


    <div class="skeleton-right text-center">
      <div class="link-border-container">
        <p id="link-rotate-left"> <%=link_to "- EVENTS -", events_path, class: "link-border-news" %></p>
      </div>
    </div>

  </div>

</div>




<div class="page hidden-sm hidden-md hidden-lg">

<%= render 'shared/navbar/navbar_vr_xs'%>

  <div class="skeleton-xs text-center hidden-sm hidden-md hidden-lg">
    <div class="skeleton-middle-xs text-center" >
      <div class="projects-content-xs hidden-sm hidden-md hidden-lg ">
          <%= render 'shared/projects/projects_vr_content_xs' %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_infos_presentation.html.erb
<div class="page hidden-xs">


  <div class= "row">
    <% @infos.each do |info| %>
    <div class= 'col-12'>
      <% if current_user %>
       <p><%= link_to "delete |", info_path(info), method: :delete, class:"link"%> <%= link_to " update", edit_info_path(info), class:"link"%></p>
      <% end %></p>
      <p id="info-name"><%= info.name %></p>
      <p id="info-localisation"><%= info.localisation%>
      <p id="info-date"><%= info.date%></p>
      <p id="info-commentary"><%= info.commentary%></p>
      <p> _ </p>
    </div>

    <% end %>

</div>


</div>

app/views/shared/navbar/_navbar.html.erb
<div class="navbar hidden-xs">
  <div class="navbar-left">
    <div class="navbar-left-links hidden-xs">
      <a><% if user_signed_in? %>
        <%= link_to "log-out |", destroy_user_session_path, method: :delete, class: "link" %>
        <% end %></a>
      <a><%if current_user %>
        <%= link_to " New project |", new_project_path, class: "link"%>
      <%end %></a>
      <a><% if current_user %>
        <%= link_to " New info |", new_info_path, class: "link"%>
      <% end %></a>
      <a><% if current_user %>
        <%= link_to " New event |", new_event_path, class: "link"%>
      <% end %></a>
      <a><% if current_user %>
        <%= link_to " New text", new_text_path, class: "link"%>
      <% end %></a>
      </div>
  </div>
  <div class="navbar-right ">
  </div>

  </div>

app/views/shared/navbar/_navbar_artwork.html.erb
<div class="navbar hidden-xs">
  <div class="navbar-left">
    <div class="navbar-left-links hidden-xs">
      <a><% if user_signed_in? %>
        <%= link_to "log-out |", destroy_user_session_path, method: :delete, class: "link" %>
        <% end %>
      <a><% if current_user %>
        <%= link_to " update |", edit_artwork_path, class: "link" %><% end %></a>
      <a><% if current_user %>
        <%= link_to " delete", artwork_path(@artwork), method: :delete, class: "link" %>
      <% end %></a>
      </div>
  </div>
  <div class="navbar-right ">

  </div>

  </div>

app/views/shared/navbar/_navbar_artwork_vr_xs.html.erb
<div class="navbar-xs hidden-sm hidden-md hidden-lg">
  <div class="navbar-left-xs">
    <div class= "home-icon" >
      <%=link_to showvr_project_path(@artwork.project) do%>
        <i class="fas fa-home" style= "font-size:1em"></i>
      <%end %>
    </div>
  </div>
  <div  class="navbar-center-xs "></div>
  <div class="navbar-right-xs ">
    <%= render'shared/navbar/dropdown' %>

  </div>

  </div>

app/views/shared/navbar/_navbar_project.html.erb
<div class="navbar hidden-xs">
  <div class="navbar-left">
    <div class="navbar-left-links hidden-xs">
      <a><% if user_signed_in? %>
        <%= link_to "log-out |", destroy_user_session_path, method: :delete, class: "link" %>
        <% end %></a>
      <a><% if current_user%>
        <%= link_to " update |", edit_project_path(@project), class: "link" %>
      <% end %></a>
      <a><% if current_user %>
        <%= link_to "delete |", project_path(@project), method: :delete, class: "link" %>
      <% end %></a>
      <a><% if current_user %>
        <%= link_to " new artwork", new_project_artwork_path(@project), class: "link" %>
      <% end %></a>
      </div>
  </div>
  <div class="navbar-right ">

  </div>

  </div>

app/views/shared/navbar/_navbar_project_vr_xs.html.erb
<div class="navbar-xs hidden-sm hidden-md hidden-lg">
  <div class="navbar-left-xs">
    <div class= "home-icon" >
      <%=link_to vr_projects_path do%>
        <i class="fas fa-home" style= "font-size:1em"></i>
      <%end %>
    </div>
  </div>
  <div  class="navbar-center-xs "></div>
  <div class="navbar-right-xs ">
    <%= render'shared/navbar/dropdown' %>

  </div>

  </div>

app/views/shared/projects/_projects_content.html.erb
<div class="projects-top-bottom hidden-xs">
  <div class="projects-title">
          <%=link_to "PAULINE | DUFOUR", infos_path, class: "link-top-title-left"%>
  </div>
  <div class="title">
          <%#=link_to "# NEWS", events_path, class: "link-top-title" %>
  </div>
</div>


        <%= render 'shared/projects/projects_presentation' %>




<div class="projects-top-bottom hidden-xs">
  <div class= "top-bottom-shadow"></div>
    <div class= "projects-title-bottom">
      <%= link_to "VIRTUAL | REALITY", vr_projects_path, class: "link-bottom-title"%>
    </div>
</div>

<div class="projects-bottom-xs text-center hidden-sm hidden-md hidden-lg">
  <div class= "title" >
          <%= link_to "VIRTUAL | REALITY", vr_projects_path, class: "link-bottom-title-xs"%>
  </div>
</div>

app/views/texts/index.html.erb
<div class="page hidden-xs">

  <%= render 'shared/navbar/navbar' %>





<div class="skeleton text-center">

  <div class="skeleton-left text-center">
    <div class="link-border-container">
    <p id="link-rotate-right">

      <% if current_user %>
      <%= link_to "- back -", infos_path, class:"link-border" %>
      <% else %>
      <%= link_to "- back -", request.referer.present? ? request.referer : default_path,  class:"link-border" %>
      <% end %>
    </p>
  </div>
   </div>


  <div class="skeleton-middle text-center">

    <div class="texts text-center hidden-xs hidden-sm ">

      <div class="texts-banner text-center hidden-xs hidden-sm ">
          <p></p>
          <p>- TEXTS -</p>
      </div>
      <div class="texts-container hidden-xs hidden-sm ">
        <div class="row">
          <% @texts.each do |text| %>
            <% if current_user %>
              <p><%= link_to "delete", text_path(text), method: :delete, class:"link"%>   <span></span><span>|</span><span></span>   <%= link_to "update", edit_text_path(text), class:"link"%></p>
            <% end %>
            <div class="text-card hidden-xs hidden-sm">
              <div></div>
              <div class="text-author-top hidden-xs hidden-sm"> <span>by</span> <span></span><%= text.author%></div>
              <div class="text-content hidden-xs hidden-sm"> <%= simple_format(text.content, class: 'text-content hidden-xs hidden-sm ')%></div>
              <div class="text-author hidden-xs hidden-sm"><%= simple_format(text.author, class: 'text-author hidden-xs hidden-sm')%></div>
               <div class="text-presentation-author hidden-xs hidden-sm"><%= simple_format(text.presentation_author, class: 'text-presentation-author hidden-sm') %></div>
              <p> - </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="texts-sm text-center hidden-xs hidden-md hidden-lg">

      <div class="texts-banner-sm text-center hidden-xs hidden-md hidden-lg">
          <p></p>
          <p>|TEXTS</p>
      </div>
      <div class="texts-container-sm hidden-xs hidden-md hidden-lg">
        <div class="row">
          <% @texts.each do |text| %>
            <% if current_user %>
              <p><%= link_to "delete", text_path(text), method: :delete, class:"link"%>   <span></span><span>|</span><span></span>   <%= link_to "update", edit_text_path(text), class:"link"%></p>
            <% end %>
            <div class="text-card-sm hidden-xs hidden-md hidden-lg ">
              <div></div>
              <div class="text-author-top"> <span>by</span> <span></span><%= text.author%></div>
              <div class="text-content-sm hidden-xs hidden-md hidden-lg "> <%= simple_format(text.content, class: 'text-content-sm hidden-xs hidden-md hidden-lg')%></div>
              <div class="text-author-sm hidden-xs hidden-md hidden-lg"><%= simple_format(text.author, class: 'text-author-sm hidden-xs hidden-md hidden-lg')%></div>
               <div class="text-presentation-author-sm hidden-xs hidden-md hidden-lg "><%= simple_format(text.presentation_author, class: 'text-presentation-author-sm hidden-xs hidden-md hidden-lg') %></div>
              <p> - </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>

  <div class="skeleton-right text-center">
    <p></p>
  </div>

</div>

</div>


<div class="page_xs hidden-sm hidden-md hidden-lg">


<%= render 'shared/navbar/navbar_texts_xs' %>


<div class="skeleton text-center">


  <div class="skeleton-middle-xs text-center">

    <div class="texts-xs text-center  hidden-sm hidden-md hidden-lg ">
      <div class="texts-container-xs">
        <div class="row">
          <% @texts.each do |text| %>
            <div class="text-card-xs hidden-sm hidden-md hidden-lg ">
              <div></div>
              <div class="text-author-top-xs"> <span>by</span> <span></span><%= text.author%></div>
              <div class="text-content-xs hidden-sm hidden-md hidden-lg "> <%= simple_format(text.content, class: 'text-content-xs hidden-sm hidden-md hidden-lg  ')%></div>
              <div class="text-author-xs hidden-sm hidden-md hidden-lg "><%= simple_format(text.author, class: 'text-author-xs hidden-sm hidden-md hidden-lg ')%></div>
               <div class="text-presentation-author-xs hidden-sm hidden-md hidden-lg "><%= simple_format(text.presentation_author, class: 'text-presentation-author-xs hidden-sm hidden-md hidden-lg ') %></div>
              <p> - </p>
            </div>
          <% end %>
        </div>
      </div>
    </div>



  </div>

</div>

</div>